---
title: "Problem Set 2"
author: "Munan Hou"
date: "October 21, 2016"
output: html_document
---

#1

```{r read.table}
data <- read.table("M1_spikes.csv", sep = ",", header = TRUE, fill = TRUE)
```

```{r subset arrivals}
cumarrivetime <- subset(data, data$spikes == 1)[,"T"]
```

```{r plot time series}
plot(1:max(cumarrivetime), rep(0,max(cumarrivetime)), type = "n")
abline(v = cumarrivetime)
```

```{r plotXY}
XY <- subset(data, data$spikes==1)[,c("X","Y")]
plot(data$X,data$Y, type="l") + points(XY)
```

```{rv phi }
Vphi <- subset(data,data$spikes==1)[,c("V","phi")]
plot(data$V,data$phi, type="l") + points(Vphi)
```

#2

```{r function}
subnum <- function(x){
  bin <- seq(min(data$phi),max(data$phi),by=(max(data$phi)-min(data$phi))/x)
  row_count <- c()
  for (i in 1:(x-1)) {
    row_count <- c(row_count, nrow(subset(data, data$phi >= bin[i] & data$phi < bin[i+1])))
  }
  row_count <- c(row_count, nrow(subset(data, data$phi >= bin[x] & data$phi <= bin[x+1])))
  return(row_count)
}
bin <- seq(min(data$phi),max(data$phi),by=(max(data$phi)-min(data$phi))/100)
h <- hist(subset(data,data$spikes==1)[,"phi"],breaks = bin, xlab = "Direction")
```

```{r bincounts}
bincounts <- subnum(100)
h$counts <- h$counts/bincounts
h$xname <- "Direction"
plot(h)
```

```{r}
range <- data.frame("lower.bound" = bin[-1], "upper.bound" = bin[-length(bin)], "freq" = h$counts)
range <- range[which(range$freq==max(range$freq)),]
range
```

As the phi is divided into 100 bins, the most likely direction this neuron is going to fire is in (-2.13486, -2.197675)

#3

```{r likelihood of data ~ f(L(theta preferred)), range of theta preferred}
lbin <- seq(min(data$phi),max(data$phi), .01)
lbincounts <- c()
for (i in 1:length(lbin)){
  lambda <- 30 + (30 / 16.1) * (cos(data$phi - lbin[i]) * data$V)
  lbincounts <- c(lbincounts, sum(log(lambda)) - sum(lambda[-1]))
  }
fisher <- -(c(0, 0, lbincounts) + c(lbincounts, 0, 0) - 2 * c(0, lbincounts, 0)) / .01^2
fisher <- fisher[2:(length(fisher) - 1)]
head(fisher)
```


```{r maximized likelihood}
mc <- data.frame("phi"=lbin, "logl"=lbincounts, "fisher"=fisher)
ml <- subset(mc, mc$logl==max(mc$logl))
ml
```

```{r 95% C.I.}
rep(ml$phi, 2) + c(-1.96 * (ml$fisher^-0.5), 1.96 * (ml$fisher^-0.5))
```

#4

```{r}
plot(data$T, 30 + 30 * data$V * cos(data$phi - .9301) / 16.1, type = "l",xlab = "time", ylab = "lambdahat")
```

#5

```{r original ISIs hist}
spiketimes <- subset(data,data$spikes==1)
spiketimes <- spiketimes[,"T"]
spiketimes
ISIs <-  c(spiketimes,0)-c(0,spiketimes)
ISIs <- ISIs[-c(1,length(ISIs))]
ISIs
hist(ISIs, xlab = 'ms')
```

```{r rescale}
spiketimes <- subset(data,data$spikes==1)
S <- 30 + 30 * spiketimes$V * cos(spiketimes$phi - .9301) / 16.1

S_mean <- (c(spiketimes$T,0)+c(0,spiketimes$T)) / 2
S_mean <- S_mean[2:(length(S_mean)-1)] 

st2 <- data[S_mean,c("V","phi")] 
S_mean <- 30+30*st2$V*cos(st2$phi-.9301) / 16.1 
b_a <- (spiketimes$T[-1]-spiketimes$T[-length(spiketimes$T)])/1000

S1 <- S[-length(S)] 
S2 <- S[-1]

re<- (S1+4*S_mean+S2)*b_a/6
hist(re)
```

```{r ks plot}

```

#6

```{r}
acf(re)
```

#7

```{r}
cum <- cumsum(re)
sb <- hist(cum,seq(min(cum)-1,max(cum)+1,1))
var(sb$counts)/mean(sb$counts)
```

```{r}
qgamma(c(0.025,0.975), length(sb$counts)/2, scale = 2/length(sb$counts))
```














































